CREATE TABLE STATIONS  (
    STATION_NAME VARCHAR(2550) PRIMARY KEY,
    PROVINCE VARCHAR(2550),
    STATION_DATE VARCHAR(2550),
    MEAN_TEMP VARCHAR(2550),
    HIGHEST_MONTHLY_MAXI_TEMP VARCHAR(2550),
    LOWEST_MONTHLY_MIN_TEMP VARCHAR(2550)
 );
  
ALTER TABLE STATIONS DROP PRIMARY KEY;
